# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - croo

on:
    push:
        branches: ["main"]
    workflow_dispatch:

# defaults:
#     run:
#         working-directory: ./express-backend

env:
    AZURE_WEBAPP_PACKAGE_PATH: ./express-backend # set this to the path to your web app project, defaults to the repository root

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - name: npm install, build, and test
              working-directory: ./express-backend
              run: |
                  npm install
                  npm run build --if-present
                  npm run test --if-present
            
              env:
                  MONGO_DB: ${{ secrets.MONGO_DB }}
                  MONGO_USER: ${{ secrets.MONGO_USER }}
                  MONGO_PWD: ${{ secrets.MONGO_PWD }}
                  MONGO_CLUSTER: ${{ secrets.MONGO_CLUSTER}}

            - name: Zip artifact for deployment
              run: zip release.zip ./* -r

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v3
              with:
                  name: node-app
                  path: express-backend/release.zip

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "Production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v3
              with:
                  name: node-app

            - name: unzip artifact for deployment
              run: unzip release.zip
              working-directory: .

            - name: "Deploy to Azure Web App"
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                  app-name: "croo"
                  slot-name: "Production"
                  publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A9D8E8C1E7564A9AB239282712B22D6E }}
                  package: .
